/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 04 23:17:50 GMT 2026
 */

package ds.seed1448;

import org.junit.Test;
import static org.junit.Assert.*;
import ds.Grafo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Evo extends Grafo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Grafo grafo0 = new Grafo(1);
      grafo0.insereAresta(0, 3878, 3878);
      grafo0.imprime();
      assertEquals(1, grafo0.numVertices());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Grafo grafo0 = new Grafo(1);
      grafo0.insereAresta(0, 3878, 3878);
      grafo0.insereAresta(0, 3878, (-2092));
      Grafo.Aresta grafo_Aresta0 = grafo0.retiraAresta(0, 3);
      assertNull(grafo_Aresta0);
      assertEquals(1, grafo0.numVertices());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Grafo grafo0 = new Grafo(498);
      Grafo grafo1 = grafo0.grafoTransposto();
      grafo1.prox = grafo0.prox;
      grafo1.insereAresta(449, 1811, 793);
      assertEquals(498, grafo1.numVertices());
      
      Grafo.Aresta grafo_Aresta0 = grafo0.retiraAresta(449, 0);
      assertNotNull(grafo_Aresta0);
      assertEquals(0, grafo_Aresta0.peso());
      assertEquals(449, grafo_Aresta0.v1());
      assertEquals(0, grafo_Aresta0.v2());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Grafo grafo0 = new Grafo(943);
      grafo0.insereAresta(4500, 0, 1926);
      boolean boolean0 = grafo0.existeAresta(0, 0);
      assertTrue(boolean0);
      assertEquals(943, grafo0.numVertices());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Grafo grafo0 = new Grafo(1);
      grafo0.insereAresta(0, 3878, 3878);
      boolean boolean0 = grafo0.existeAresta(0, (-130));
      assertEquals(1, grafo0.numVertices());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Grafo grafo0 = new Grafo(1);
      grafo0.insereAresta(0, 3878, 3878);
      int[] intArray0 = new int[3];
      grafo0.cab = intArray0;
      grafo0.insereAresta(0, 3878, (-2092));
      grafo0.insereAresta(2360, (-1587), 0);
      assertEquals(1, grafo0.numVertices());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Grafo grafo0 = new Grafo(0);
      int int0 = grafo0.numVertices();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Grafo grafo0 = new Grafo(943);
      grafo0.insereAresta(4500, 0, 1926);
      Grafo grafo1 = grafo0.grafoTransposto();
      assertEquals(943, grafo0.numVertices());
      assertEquals(943, grafo1.numVertices());
  }
}
