/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 04 23:11:56 GMT 2026
 */

package ds.seed1448;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ds.FPHeapMax;
import ds.Item;
import ds.MeuItem;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Evo extends FPHeapMax_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(487);
      Item[] itemArray0 = new Item[5];
      fPHeapMax0.copia(itemArray0);
      // Undeclared exception!
      try { 
        fPHeapMax0.imprime();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(487);
      fPHeapMax0.imprime();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(0);
      try { 
        fPHeapMax0.insere((Item) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Erro: heap cheio
         //
         verifyException("ds.FPHeapMax", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(487);
      MeuItem meuItem0 = new MeuItem(0);
      Item[] itemArray0 = new Item[5];
      itemArray0[2] = (Item) meuItem0;
      fPHeapMax0.copia(itemArray0);
      try { 
        fPHeapMax0.insere(meuItem0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(487);
      MeuItem meuItem0 = new MeuItem(0);
      fPHeapMax0.insere(meuItem0);
      assertEquals(4, meuItem0.tamanho());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(0);
      try { 
        fPHeapMax0.aumentaChave(0, (Object) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Erro: chaveNova com valor null
         //
         verifyException("ds.FPHeapMax", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(0);
      try { 
        fPHeapMax0.retiraMax();
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Erro: heap vazio
         //
         verifyException("ds.FPHeapMax", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(519);
      Item[] itemArray0 = new Item[5];
      fPHeapMax0.copia(itemArray0);
      // Undeclared exception!
      try { 
        fPHeapMax0.constroi();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(487);
      fPHeapMax0.constroi();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(496);
      MeuItem meuItem0 = new MeuItem(496);
      Item[] itemArray0 = new Item[5];
      itemArray0[2] = (Item) meuItem0;
      itemArray0[3] = (Item) meuItem0;
      itemArray0[4] = (Item) meuItem0;
      fPHeapMax0.copia(itemArray0);
      Item item0 = fPHeapMax0.retiraMax();
      assertNull(item0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(496);
      Item[] itemArray0 = new Item[5];
      MeuItem meuItem0 = new MeuItem(496);
      itemArray0[2] = (Item) meuItem0;
      MeuItem meuItem1 = new MeuItem(2826);
      itemArray0[3] = (Item) meuItem1;
      fPHeapMax0.copia(itemArray0);
      try { 
        fPHeapMax0.retiraMax();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(487);
      MeuItem meuItem0 = new MeuItem(0);
      Item[] itemArray0 = new Item[5];
      itemArray0[2] = (Item) meuItem0;
      itemArray0[3] = (Item) meuItem0;
      fPHeapMax0.copia(itemArray0);
      MeuItem meuItem1 = new MeuItem((-2481));
      fPHeapMax0.insere(meuItem1);
      try { 
        fPHeapMax0.retiraMax();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(1);
      fPHeapMax0.refaz(1, 1);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FPHeapMax fPHeapMax0 = new FPHeapMax(1);
      Item item0 = fPHeapMax0.max();
      assertNull(item0);
  }
}
