/*
 * This file was automatically generated by EvoSuite
 * Tue Jan 06 21:13:58 GMT 2026
 */

package ds;

import org.junit.Test;
import static org.junit.Assert.*;
import ds.CasamentoAproximado;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class CasamentoAproximado_ESTest extends CasamentoAproximado_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CasamentoAproximado.shiftAndAproximado("Casamento na posicao: ", 1, "Casamento na posicao: ", (-1), 1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CasamentoAproximado.shiftAndAproximado("/dR)+gPI", 1, "/dR)+gPI", 1, 0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CasamentoAproximado casamentoAproximado0 = new CasamentoAproximado();
  }
}
